Библиотеки:  
NumPy работа с числовыми массивами  
matplotlib построение графиков  
SciPy функции для научных вычислений  
pandas  таблицы (как matrix и data.frame в R)  
Scikit-learn алгоритмы машинного обучения  
PythonSeaborn визуализация статических данных  


In [1]:
from numpy import *


In [5]:
a=array([2,3,4])#создание одномерного массива из списка целых чисел

In [3]:
print(a)
a

[2 3 4]


array([2, 3, 4])

In [4]:
a.ndim #размерность массива

1

In [7]:
a.shape #размеры массива (число строк, столбцов и т.д.)

(3,)

In [9]:
b=array([(1.5,2,3),(4,5,6)])#двумерный массив

In [11]:
print(b) #все числа имеют один тип - число с плавающей точкой

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [15]:
b.size

6

In [16]:
z=zeros((3,2))

In [17]:
z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
 arange(10,30,5)#функция arange аналогичена функции range, но возвращает массив

array([10, 15, 20, 25])

In [19]:
linspace(0,2,9)#генерирует 9 чисел на отрезке от 0 до 2 с равным шагом

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
b=arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [24]:
a=array([10,20,30])
b=arange(3)
print(a)
print(b)

[10 20 30]
[0 1 2]


In [26]:
print(a+b)
print(a-b)

[10 21 32]
[10 19 28]


In [27]:
print(a**2)

[100 400 900]


In [28]:
2*sin(a)

array([-1.08804222,  1.8258905 , -1.97606325])

In [29]:
a<20

array([ True, False, False])